- name: Prüfe und kopiere Datei vom Control Node zum Server
  hosts: localhost
  tasks:
    - name: Überprüfen, ob die Datei existiert
      stat:
        path: ~/datei  # Datei auf dem Control Node
      register: file_check

    - name: Ausgabe bei fehlender Datei (Fehlermeldung in rot)
      debug:
        msg: "\033[1;31m[FEHLER] Datei existiert auf Ursprungssystem nicht!\033[0m"
      when: not file_check.stat.exists
      failed_when: not file_check.stat.exists 

- name: Kopiere Datei vom Control Node auf den Server
  hosts: ubuntu_server
  tasks:
    - name: Kopiere Datei nur, wenn sie existiert
      copy:
        src: ~/datei
        dest: /tmp/datei  
        mode: "0644"
      when: file_check.stat.exists  # Nur ausführen, wenn die Datei existiert
