----
- name: Prüfe und kopiere Datei vom Command Host -> Server
  hosts: localhost
  tasks: 
    - name: Prüfe ob datei Existiert
      stat: 
        path: ~/datei
      register: file_check
    
    - name: "Datei Fehlt -> Fehlermeldung"
      debug:
        msg: "\033[1;31mFEHLER] DATEI EXISTIERT AUF URSPRUNGSSYSTEM NICHT!\033[0m"
      when: not file_check.stat.exists  
      failed_when: not file_check.stat.exists  

--     
- name: Kopiere Datei vom Command Host -> Server
  hosts: ubuntuserver
  tasks: 
    - name: Kopiere Datei wenn vorhanden
      copy:
        src: ~/datei
        dest: /tmp/datei
        mode: "0644"
      when: file_check.stat.exists  