---
- name: Install and configure dnsmasq and UFW.
  hosts: ubuntuserver
  become: true
  gather_facts: true

  tasks:
    - name: Install dnsmasq
      ansible.builtin.apt:
        name: dnsmasq
        update_cache: true
      notify: Enable Service

    - name: Ensure dnsmasq.conf exists
      ansible.builtin.copy:
        dest: /etc/dnsmasq.conf
        content: ""
        mode: '0644'
        force: false

    - name: Append DHCP configuration if not present
      ansible.builtin.blockinfile:
        path: /etc/dnsmasq.conf
        block: |
          interface=enp0s8
          bind-interfaces
          dhcp-range=192.168.100.10,192.168.100.20,24h
          # exclude loopback interface
          except-interface="lo"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - DHCP CONFIGURATION"
      notify: Restart dnsmasq

    - name: Allow firewall rules for dnsmasq and related services
      community.general.ufw:
        rule: allow
        port: "{{ item.port }}"
        proto: "{{ item.proto }}"
        state: enabled
      loop:
        # - { port: '22', proto: 'tcp' }     # SSH
        - { port: '67', proto: 'udp' }     # DHCP Server
        - { port: '68', proto: 'udp' }     # DHCP Client
        # - { port: '53', proto: 'udp' }     # DNS (UDP)
        # - { port: '53', proto: 'tcp' }     # DNS (TCP)
        # - { port: '137', proto: 'udp' }    # NetBIOS Name Service
        # - { port: '138', proto: 'udp' }    # NetBIOS Datagram Service
        # - { port: '139', proto: 'tcp' }    # NetBIOS Session Service
        # - { port: '445', proto: 'tcp' }    # Microsoft-DS (Samba)

  handlers:
    - name: Restart dnsmasq
      ansible.builtin.systemd:
        name: dnsmasq
        state: restarted

    - name: Enable Service
      ansible.builtin.systemd:
        name: dnsmasq
        enabled: true
        
