---
- name: Install and configure dnsmasq and UFW.
  hosts: ubuntuserver
  become: true
  gather_facts: true

  tasks:
    - name: Install dnsmasq
      apt:
        name: dnsmasq
        update_cache: true
      notify: Enable Service

    - name: Ensure dnsmasq.conf exists
      copy:
        dest: /etc/dnsmasq.conf
        content: ""
        mode: '0644'
        force: false

    - name: Append DHCP configuration if not present
      blockinfile:
        path: /etc/dnsmasq.conf
        block: |
          interface=enp0s8
          bind-interfaces
          dhcp-range=192.168.100.10,192.168.100.20,24h
          # exclude loopback interface
          except-interface="lo"
        marker: "# {mark} ANSIBLE MANAGED BLOCK - DHCP CONFIGURATION"
      notify: Restart dnsmasq

    - name: Allow firewall rules for dnsmasq and related services
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: "{{ item.split('/')[-1] }}"
      with_items:
        - '22/tcp'         # SSH
        - '67/udp'         # DHCP Server
        - '68/udp'         # DHCP Client
        - '53/udp'         # DNS (UDP)
        - '53/tcp'         # DNS (TCP)
        - '137/udp'        # NetBIOS Name Service
        - '138/udp'        # NetBIOS Datagram Service
        - '139/tcp'        # NetBIOS Session Service
        - '445/tcp'        # Microsoft-DS (Samba)

  handlers:
    - name: Restart dnsmasq
      systemd:
        name: dnsmasq
        state: restarted
    - name: Enable Service
      systemd_service:
        name: dnsmasq
        enabled: true
